version: 2
jobs:
  python_learning_environment:
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/Wach-E/setup-demo/compare/3311da1aa5570c8c687feb16387cece08d32a0b8...3311da1aa5570c8c687feb16387cece08d32a0b8
    - level: lesson-2
    docker:
    - image: cimg/python:3.8:10
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          source venv/bin/activate
          make install
          # Install and setup hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run lint
        command: |
          source venv/bin/activate
          make lint
          echo "$level is moving"
workflows:
  version: 2
  python_env_workflow:
    jobs:
    - python_learning_environment
