# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  python_learning_environment:
    environment:
      imageName: devops_lesson_two 
    # specity what will execute steps
    docker:
      - image: cimg/python:3.10.0-node
        auth:
          # Project Environmental variables
          username: $dockerhub_username
          password: $dockerhub_password
    
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build, tag and push ML environment image
          command: |
            docker build -t $imageName .
            docker tag $imageName $dockerhub_username/$imageName
            echo "$dockerhub_password" | docker login --username $dockerhub_username --password-stdin
            docker push $dockerhub_username/$imageName

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-


      
      # - run:
      #     name: install dependencies
      #     command: |
      #       make init_setup
      #       # Install and setup hadolint
      #       wget https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
      #       mv hadolint-Linux-x86_64 hadolint
      #       chmod +x hadolint
      #       sudo mv hadolint /usr/local/bin/hadolint

      # - save_cache:
      #     paths:
      #       - ./setup_env
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}

      # - run:
      #     name: run lint
      #     command: |
      #       make activate
      #       make lint
      #       echo "$level shows $stack is dope!"

workflows:
  version: 2
  "python_env_workflow":
      jobs:
        - python_learning_environment:
            context:
              - docker credentials
           

